name: 'Jelastic redeploy image'
author: 'abashek'
description: 'Trigger API to redeploy container'
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  login:
    description: 'Login for api '
    required: true
  password:
    description: 'Password for api '
    required: true
  env-name:
    description: 'environment name in jelastic dashboard'
    required: true
  host:
      description: 'api host (app.platform.com)'
      required: true
  node-id:
    description: 'target NodeId'
    required: true
  action:
    description: 'deployarchive | redeploy'
    required: true
  tag:
    description: 'docker image tag'
    required: false
  fileUrl:
    description: 'Url to archive'
    required: false
outputs:
  results:
    description: 'Log of api requests'
runs:
  using: 'node12'
  main: 'index.js'
